name : Deploy React to Github Pages

on:
  push:
    branches:
      - fronend-only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkpoint
        uses: actions/checkout@v4

      - name : Set up NodeJs
        uses : actions/setup-node@v4
        with :
          node-version: '20'
      - name: GotoApp
        run : cd app
      
      - name : Install dep
        run : bun i
          
      - name : Build React app
        run : bun run build

      - name : Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dirL: ./app/dist
      
          