# ‡∏ä‡∏∑‡πà‡∏≠ ci/cd
name : My First Workflow

#
on :
  push :
    # 
    branches:
      - main
# 
jobs :
  build :
    # deploy system
    runs-on : ubuntu-lastest
  
    # ‡∏Ç‡∏±‡πâ‡∏ô‡∏ï‡∏≠‡∏ô‡∏Ç‡∏≠‡∏á workflows
    steps :
    # ‡πÄ‡∏≠‡∏≤‡πÇ‡∏Ñ‡πâ‡∏î‡∏°‡∏≤‡∏à‡∏≤‡∏Å repo
    - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

    - name: Say Hello
    # script to run in linux
      run : echo "Hello, Github Action"
  deploy:
      uses: guzamak/github-pages-deploy-action@v4
      with:
        folder: ./